# Generated by Django 3.1.7 on 2021-04-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
