# Generated by Django 3.1.7 on 2021-04-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210403_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Todo List', 'verbose_name_plural': 'Todo Lists'},
        ),
    ]
